//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voorraad
    {
        public Nullable<int> Voorraad1 { get; set; }
        public int VestigingID { get; set; }
        public int ProductID { get; set; }
        public string Product_Name { get; set; }
        public string Vestiging_Name { get; set; }
        public int VoorraadID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vestiging Vestiging { get; set; }
    }
}
